<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="bi3.tests.fnb.CustomerReturnTest" tests="2" time="3.647" ignored="0" failures="0" timestamp="05 May 2017 22:42:42 GMT" skipped="1" hostname="Bi3-NB-RASHARD" errors="1">
  <testcase name="CustomerOrderCreation" time="3.647" classname="bi3.tests.fnb.CustomerReturnTest">
    <skipped/>
  </testcase> <!-- CustomerOrderCreation -->
  <testcase name="Initialize" time="0.000" classname="bi3.tests.fnb.CustomerReturnTest">
    <error type="bi3.framework.exceptions.FrameworkException" message="ERROR in ExcelFileReader">
      <![CDATA[bi3.framework.exceptions.FrameworkException: ERROR in ExcelFileReader
	at bi3.framework.util.ExcelUtil.<init>(ExcelUtil.java:79)
	at bi3.tests.fnb.CustomerReturnTest.Initialize(CustomerReturnTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at bi3.framework.util.ExcelUtil.<init>(ExcelUtil.java:64)
	... 28 more
]]>
    </error>
  </testcase> <!-- Initialize -->
</testsuite> <!-- bi3.tests.fnb.CustomerReturnTest -->
